/**
 * The length of a UID generated by {@link Date.getTime}.
 *
 * This is a relatively lazy implementation, as the length of UIDs will either
 * reset to 0 in 2038 (The Epochalypse) or eventually increment to 14 digits...
 * in 2286. It's fine for now, I guess.
 */
const UID_LENGTH = 13

/**
 * Create a new UID for tokens.
 * @returns A unique ID number.
 */
function makeUid() {
    return new Date().getTime();
}

/**
 * Create a token with the given properties, and spawn it on the grimoire
 * in the specified location.
 * @param {String} id The role ID of the token: what role it has.
 * @param {Number} uid The Unique ID of the token: a unqiue identifier to the token
 * even if its role changes over time.
 * @param {"show"|"hide"|"bluff"} visibility How the token appears. Show means
 * it appears in Town Square mode. Bluff means it's a demon bluff. Hide means
 * it's only here for internal use.
 * @param {String} cat The category of the token: what role type it is.
 * @param {"alive"|"dead"|"dead_vote"} viability The life/death state of the
 * token, and if the player can vote.
 * @param {Number} left The offset, in pixels, from the left edge of the screen.
 * @param {Number} top The offset, in pixels, from the top edge of the screen.
 * @param {*} nameText The name to appear under the token.
 */
function spawnToken(id, uid, visibility, cat, hide_face, viability, left, top, nameText, reminders) {
    // Force tokens to appear if we try to add one. 
    if (document.getElementById("body_actual").getAttribute("night") == "true") {
        visibility_toggle()
    }

    // The div.
    var div = document.createElement("div");
    div.setAttribute("onclick", "javascript:infoCall('" + id + "', " + uid + ")");
    div.classList = "role_token drag";
    div.style = `background-image: url('assets/token.png'); left:${left}; top:${top}`
    div.id = id + "_token_" + uid;
    div.setAttribute("role", id);
    div.setAttribute("viability", viability);
    div.setAttribute("uid", uid);
    div.setAttribute("visibility", visibility);
    div.setAttribute("cat", cat);
    div.setAttribute("show_face", !hide_face);

    let imageLink = getTokenImageLink(id);

    // Actual picture.
    var role = document.createElement("img");
    role.src = imageLink;
    role.id = `${id}_${uid}_image`;
    role.classList = "token_image background_image";
    div.appendChild(role);

    // The token name. 
    var roleName = createRoleNameElement(id, uid);
    div.appendChild(roleName);

    // Death shroud.
    var death = document.createElement("img");
    death.src = "assets/shroud.png";
    death.classList = "token_death";
    death.id = id + "_" + uid + "_death";
    div.appendChild(death);

    // The icon indicating if this token is hidden in TS (bluff, reminder, etc)
    var visibility_pip = document.createElement("div");
    visibility_pip.classList = "token_visibility_pip background_image";
    visibility_pip.id = id + "_" + uid + "_visibility_pip";
    div.appendChild(visibility_pip);

    // Dead vote (TS mode)
    var vote = document.createElement("img");
    vote.src = "assets/vote_token.png";
    vote.classList = "token_vote";
    vote.id = id + "_" + uid + "_vote";
    div.appendChild(vote);

    // The role of travelers, when shown in TS mode. 
    var outsider_betray = document.createElement("div");
    if (cat == "traveller") {
        outsider_betray.style.backgroundImage = `url('${imageLink}')`
    }
    outsider_betray.classList = "token_outsider_betray background_image";
    outsider_betray.id = id + "_" + uid + "_outsider_betray";
    div.appendChild(outsider_betray);

    // Player name, if given.
    var name = document.createElement("span")
    name.innerHTML = nameText;
    name.classList = "token_text"
    name.id = id + "_name_" + uid;
    div.appendChild(name);

    document.getElementById("token_layer").appendChild(div);

    // Add reminder tokens
    for (const reminder of reminders) {
        let reminderHTML;
        if (reminder.length == 3) {
            reminderHTML = spawnReminder(reminder[0], reminder[1], reminder[2], '-50px', '0px');
        } else {
            reminderHTML = dragPipLayerSpawn(reminder[0], '-50px', '0px', "false");
        }
        reminderHTML.style.position = "relative";
        div.appendChild(reminderHTML);
    }
    // Random admin stuff.
    update_role_counts();
    validateSetup();
    makeDraggable(div);
    populate_night_order();

    // This function is used by the loading code to place all the tokens.
    if (!loading) { save_game_state(); }
}

/**
 * Generate the role name graphic that appears at the bottom of the token.
 * This is a SVG that curves along the bottom.
 * @param {String} id The role ID of the token.
 * @param {String} uid The Unique ID of the token.
 * @returns an HTML SVG element that contains the name of the role.
 */
function createRoleNameElement(id, uid) {
    var roleName = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    roleName.setAttribute("viewBox", "0 0 150 150");
    roleName.classList.add("token_role_name");

    // Create the path element
    var path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", "M 13 75 C 13 150, 138 150, 138 75");
    path.setAttribute("id", "curve");
    path.setAttribute("fill", "transparent");
    roleName.appendChild(path);

    // Create the text element
    var text = document.createElementNS("http://www.w3.org/2000/svg", "text");
    text.setAttribute("width", "150");
    text.setAttribute("x", "62.5%");
    text.setAttribute("y", "130");
    text.setAttribute("text-anchor", "middle");

    // Create the textPath element
    var textPath = document.createElementNS("http://www.w3.org/2000/svg", "textPath");
    textPath.setAttributeNS("http://www.w3.org/1999/xlink", "href", "#curve"); // Use setAttributeNS for xlink
    textPath.setAttribute("style", "fill: black; font-family: Dumbledor; font-size: 24px;");
    textPath.classList.add("js--character--name");
    textPath.id = `${id}_${uid}_name_text`;
    textPath.textContent = roles[id]["name"]; // Use textContent for dynamic text

    // Append textPath to text, and text to svg
    text.appendChild(textPath);
    roleName.appendChild(text);

    return roleName;
}

/**
 * Extract a link to the image of the token used here. 
 * @param {*} id 
 * @returns 
 */
function getTokenImageLink(id) {
    const image = roles[id]["image"];
    if (typeof image === "object") {
        // in the BOTC schema, the "image" object can be either a single link,
        // or an array of links. 
        // This future-proofs us against 
        return image[0];
    }
    return image;
}

/**
 * Spawn a generic token with the given id, visibility, and role type
 * information.
 * See {@link spawnToken} for more details.
 * @param {String} id The role ID to spawn as a token.
 * @param {String} cat The role type that this role is.
 * @param {null|"true"|"false"} hide_face Whether to show or hide the face. 
 */
function spawnTokenDefault(id, cat, hide_face) {
    spawnToken(id, makeUid(), "show", cat, hide_face, "alive", (parseInt(window.visualViewport.width / 2) - 75) + "px", "calc(50% - 75px)", "", []);
}

/**
 * Remove a token from the grimoire.
 * @param {String} id The role ID of the token.
 * @param {String} uid The Unique ID of the token.
 */
function remove_token(id, uid) {
    rm = document.getElementById(id + "_token_" + uid);
    rm.parentNode.removeChild(rm);
    clean_tokens(uid);
    update_role_counts();
    validateSetup();
    hideInfo();
    populate_night_order();
}

/**
 * Create a fake "sample" token. This token doesn't have any logic assosicated
 * with it, and is only used in places where tokens are purely for display.
 * @param {*} id The role ID of the token.
 * @param {*} el The element that should take on the sample token attributes.
 * It will be completely overwritten.
 * @returns The sample token element.
 */
function generateSampleToken(id, el) {
    // TODO: this should either not return anything,
    // or not take in an element parameter.
    el.textContent = "";

    var token = document.createElement("img");
    token.src = "assets/token.png"
    token.style.width = "100%";
    token.style.height = "100%";
    el.appendChild(token);

    var role = document.createElement("img");
    role.id = "info_img_role";
    role.style.position = "absolute";
    role.src = getTokenImageLink(id);
    el.appendChild(role);

    var roleName = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    roleName.setAttribute("viewBox", "0 0 150 150");
    roleName.classList.add("token_role_name");

    // Curvature
    var path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", "M 13 75 C 13 150, 138 150, 138 75");
    path.setAttribute("id", "curve");
    path.setAttribute("fill", "transparent");
    roleName.appendChild(path);

    // Text
    var text = document.createElementNS("http://www.w3.org/2000/svg", "text");
    text.setAttribute("width", "150");
    text.setAttribute("x", "62.5%");
    text.setAttribute("y", "130");
    text.setAttribute("text-anchor", "middle");

    // Create the textPath element
    var textPath = document.createElementNS("http://www.w3.org/2000/svg", "textPath");
    textPath.setAttributeNS("http://www.w3.org/1999/xlink", "href", "#curve");
    textPath.setAttribute("style", "fill: black; font-family: Dumbledor; font-size: 24px;");
    textPath.classList.add("js--character--name");
    textPath.textContent = roles[id]["name"];

    text.appendChild(textPath);
    roleName.appendChild(text);
    el.appendChild(roleName);

    return el;
}

/**
 * Attempt to attach this token to some other token on the grimoire. 
 * Currently, this attaches reminder tokens to actual tokens. 
 * This can be leveraged to attach any two tokens.
 * @param {HTMLElement} div The token that will be attached to something else.
 * @returns if an attachment was made.
 */
function attachTokenToToken(div) {
    if (document.getElementById("attach_toggle").style.backgroundColor != "green") return false;
    if (div.getAttribute("class") == "reminder drag") {
        const players = document.getElementById("token_layer").getElementsByClassName("role_token");
        const left = parseInt(getComputedStyle(div).getPropertyValue('left'))
        const top = parseInt(getComputedStyle(div).getPropertyValue('top'))
        for (const player in players) {
            if (!isNaN(parseInt(player))) {
                try {
                    playerstyle = getComputedStyle(players[player]);

                    diffx = parseInt(playerstyle.getPropertyValue('left')) + 37.5 - left;
                    diffy = parseInt(playerstyle.getPropertyValue('top')) + 37.5 - top;
                    if (Math.sqrt(diffx * diffx + diffy * diffy) < 75) {
                        players[player].appendChild(div);
                        div.style.position = 'relative'
                        div.style.left = '-50px'
                        div.style.top = '0px'
                        //update night order
                        populate_night_order()
                        return true;
                    }
                } catch (error) { console.error(error) }
            }
        }
    }
    return false;
}

